export const ROSTER: Record<number, { name: string; pin: string }[]> = {
  0: [
    { name: "Praya Sasmita", pin: "1011" },
    { name: "Nana Masna", pin: "1012" },
    { name: "Sabar Tambun", pin: "1013" },
    { name: "Bubun", pin: "1014" },
    { name: "Kuryana", pin: "1015" },
    { name: "Andri", pin: "1016" },
  ],
  1: [
    { name: "Eris", pin: "2011" },
    { name: "Rukman", pin: "2012" },
    { name: "H.Rohmana", pin: "2013" },
  ],
  2: [
    { name: "Indra Jaelani", pin: "3011" },
    { name: "Hera", pin: "3012" },
    { name: "Tantan Rudi", pin: "3013" },
    { name: "Bayu", pin: "3014" },
    { name: "Wowo", pin: "3015" },
    { name: "Hakim", pin: "3016" },
    { name: "Andriana Taufik", pin: "3017" },
  ],
  3: [
    { name: "Dedi Mulyadi", pin: "4011" },
    { name: "Sarifudin", pin: "4012" },
    { name: "Arif Sarifudin", pin: "4013" },
    { name: "Andri Sumpena", pin: "4014" },
    { name: "Maryana", pin: "4015" },
    { name: "Acep", pin: "4016" },
    { name: "Dodi", pin: "4017" },
  ],
  4: [
    { name: "Adis Rohmana", pin: "5011" },
    { name: "Ase Ojing", pin: "5012" },
    { name: "Ence", pin: "5013" },
    { name: "Juju Supriadi", pin: "5014" },
    { name: "Wawan", pin: "5015" },
  ],
  5: [
    { name: "Sule", pin: "6011" },
    { name: "Hanafi", pin: "6012" },
    { name: "Ahmad Farid", pin: "6013" },
    { name: "Asep Hendrajat", pin: "6014" },
    { name: "Atang Sutisna", pin: "6015" },
    { name: "Eka", pin: "6016" },
    { name: "Imam", pin: "6017" },
    { name: "Oyo/Ona", pin: "6018" },
  ],
  6: [
    { name: "Yadi Mulyadi", pin: "7011" },
    { name: "Mahmudin", pin: "7012" },
    { name: "Ustadz Momon", pin: "7013" },
    { name: "Ustadz Aep", pin: "7014" },
    { name: "Saepudin", pin: "7015" },
    { name: "Roni", pin: "7016" },
    { name: "Cecep", pin: "7017" },
  ],
};
